=== Manko10/navigation-viewing-framework/configs/config.dtd
<!--
  Navigation and Viewing Framework
  Document Type Definition for XML configuration files

  Naming convention for files:
  device_types_used_(desktopusers)(powerwallusers)(ovrusers).xml
  -->

  <!ELEMENT setup (global, device+, user+)>
  
  <!ELEMENT global (transmitteroffset, groundfollowing, animatecoupling, movementtraces)>
  <!ELEMENT groundfollowing (activated, raystartheight)>
  <!ELEMENT activated (#PCDATA)>
  <!ELEMENT raystartheight (#PCDATA)>
  <!ELEMENT movementtraces (#PCDATA)>
  <!ELEMENT animatecoupling (#PCDATA)>
  
  <!ELEMENT device (type, inputsensor, trackingstation, display+, avatartype, transmitteroffset, notrackingposition, platformpos, platformrot, platformsize)>
  <!ELEMENT type (#PCDATA)>
  <!ELEMENT inputsensor (#PCDATA)>
  <!ELEMENT trackingstation (#PCDATA)>
  <!ELEMENT display (#PCDATA)>
  <!ELEMENT avatartype (#PCDATA)>
  <!ELEMENT platformpos (x, y, z)>
  <!ELEMENT x (#PCDATA)>
  <!ELEMENT y (#PCDATA)>
  <!ELEMENT z (#PCDATA)>
  <!ELEMENT platformrot (yaw)>
  <!ELEMENT yaw (#PCDATA)>
  <!ELEMENT platformsize (width, depth)>
  <!ELEMENT width (#PCDATA)>
  <!ELEMENT depth (#PCDATA)>

  <!ELEMENT user (stereo, headtrackingstation, startplatform, warnings)>
  <!ELEMENT stereo (#PCDATA)>
  <!ELEMENT headtrackingstation (#PCDATA)>
  <!ELEMENT startplatform (#PCDATA)>
  <!ELEMENT warnings (#PCDATA)>

=== Manko10/navigation-viewing-framework/configs/NEW_one_large_powerwall.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "config.dtd">

<setup>

  <global>

    <groundfollowing>
      <activated>True</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <animatecoupling>True</animatecoupling>
    <movementtraces>True</movementtraces>

  </global>

  <device>

    <type>NewSpheron</type>

    <inputsensor>device-new-spheron</inputsensor>

    <trackingstation>tracking-new-spheron</trackingstation>

    <display>large_powerwall</display>

    <avatartype>joseph</avatartype>

    <transmitteroffset>
      <x>0.0</x>
      <y>0.043</y>
      <z>1.6</z>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.75</y>
      <z>1.5</z>
    </notrackingposition>

    <platformpos>
      <x>0.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

    <platformsize>
      <width>3.8</width>
      <depth>3.6</depth>
    </platformsize>

  </device>

  <!-- First User -->
  
  <user>

    <stereo>True</stereo>

    <startplatform>0</startplatform>

    <warnings>True</warnings>

  </user>


</setup>

=== Manko10/navigation-viewing-framework/configs/atalante_two_desktop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "config.dtd">

<setup>

  <global>

    <groundfollowing>
      <activated>True</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <animatecoupling>True</animatecoupling>
    <movementtraces>True</movementtraces>

  </global>

  <device>

    <type>Spacemouse</type>

    <inputsensor>device-spacemouse</inputsensor>

    <display>atalante_display</display>

    <avatartype>joseph</avatartype>

    <transmitteroffset>
      <x>0.0</x>
      <y>0.043</y>
      <z>1.6</z>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.0</y>
      <z>0.6</z>
    </notrackingposition>

    <platformpos>
      <x>-2.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

  </device>   

  <!-- First User -->
  
  <user>

    <vip>False</vip>

    <startplatform>0</startplatform>

    <warnings>False</warnings>

  </user>

  <!-- Second User -->
  
  <user>

    <vip>False</vip>

    <startplatform>0</startplatform>

    <warnings>False</warnings>

  </user>

</setup>

=== Manko10/navigation-viewing-framework/configs/perseus_table.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "config.dtd">

<setup>

  <global>

    <groundfollowing>
      <activated>False</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <animatecoupling>True</animatecoupling>
    <movementtraces>True</movementtraces>

  </global>

  <device>

    <type>Spacemouse</type>

    <inputsensor>device-spacemouse</inputsensor>

    <display>touch_table</display>

    <avatartype>joseph</avatartype>

    <transmitteroffset>
      <x>0.0</x>
      <y>0.043</y>
      <z>1.6</z>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.75</y>
      <z>0.0</z>
    </notrackingposition>

    <platformpos>
      <x>0.0</x>
      <y>20.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

  </device>

  <!-- First User -->
  
  <user>

    <stereo>False</stereo>

    <startplatform>0</startplatform>

    <warnings>False</warnings>

  </user>
   
</setup>

=== Manko10/navigation-viewing-framework/configs/nestor_daedalos_separate_navigation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "config.dtd">

<setup>

  <global>

    <animatecoupling>True</animatecoupling>

  </global>

  <device>

    <type>KeyboardMouse</type>
    
    <display>nestor_display</display>

    <avatartype>joseph</avatartype>

    <transmitteroffset>
      <x>0.0</x>
      <y>0.043</y>
      <z>1.6</z>
      <rx>0.0</rx>
      <ry>0.0</ry>
      <rz>0.0</rz>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.2</y>
      <z>0.6</z>
    </notrackingposition>

    <platformpos>
      <x>-2.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

    <groundfollowing>
      <activated>True</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <movementtraces>True</movementtraces>

  </device>


  <device>

    <type>XBoxController</type>
    
    <inputsensor>device-xbox-1</inputsensor>    

    <display>daedalos_display</display>

    <avatartype>joseph</avatartype>

    <transmitteroffset>
      <x>0.0</x>
      <y>0.043</y>
      <z>1.6</z>
      <rx>0.0</rx>
      <ry>0.0</ry>
      <rz>0.0</rz>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.2</y>
      <z>0.6</z>
    </notrackingposition>

    <platformpos>
      <x>-2.0</x>
      <y>0.0</y>
      <z>10.0</z>
    </platformpos>

    <platformrot>
      <yaw>180.0</yaw>
    </platformrot>

    <groundfollowing>
      <activated>True</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <movementtraces>True</movementtraces>

  </device>
        

  <!-- First User Nestor -->
  
  <user>

    <vip>False</vip>

    <startplatform>0</startplatform>

    <warnings>False</warnings>

  </user>

  <!-- First User Daedalos -->
  
  <user>

    <vip>False</vip>

    <startplatform>1</startplatform>

    <warnings>False</warnings>

  </user>


</setup>

=== Manko10/navigation-viewing-framework/configs/nestor_apollo_separate_navigation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "config.dtd">

<setup>

  <global>

    <groundfollowing>
      <activated>True</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <animatecoupling>True</animatecoupling>
    <movementtraces>True</movementtraces>

  </global>

  <device>

    <type>Spacemouse</type>

    <inputsensor>device-spacemouse</inputsensor>

    <display>nestor_display</display>

    <avatartype>joseph</avatartype>

    <transmitteroffset>
      <x>0.0</x>
      <y>0.043</y>
      <z>1.6</z>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.0</y>
      <z>0.6</z>
    </notrackingposition>

    <platformpos>
      <x>-2.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

  </device>

  <device>

    <type>KeyboardMouse</type>

    <display>atalante_display</display>

    <avatartype>joseph</avatartype>

    <transmitteroffset>
      <x>0.0</x>
      <y>0.043</y>
      <z>1.6</z>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.0</y>
      <z>0.6</z>
    </notrackingposition>

    <platformpos>
      <x>-2.0</x>
      <y>0.0</y>
      <z>10.0</z>
    </platformpos>

    <platformrot>
      <yaw>180.0</yaw>
    </platformrot>

  </device>

  <!-- First User -->
  
  <user>

    <stereo>True</stereo>

    <startplatform>0</startplatform>

    <warnings>False</warnings>

  </user>
  

  <!-- Second User -->
  
  <user>

    <stereo>True</stereo>

    <startplatform>1</startplatform>

    <warnings>False</warnings>

  </user>
   
</setup>
