=== Manko10/navigation-viewing-framework/configs/config.dtd
<!--
  Navigation and Viewing Framework
  Document Type Definition for XML configuration files

  Naming convention for files:
  device_types_used_(desktopusers)(powerwallusers)(ovrusers).xml
  -->

  <!ELEMENT setup (global, device+, user+)>
  
  <!ELEMENT global (transmitteroffset, groundfollowing, animatecoupling, movementtraces)>
  <!ELEMENT groundfollowing (activated, raystartheight)>
  <!ELEMENT activated (#PCDATA)>
  <!ELEMENT raystartheight (#PCDATA)>
  <!ELEMENT movementtraces (#PCDATA)>
  <!ELEMENT animatecoupling (#PCDATA)>
  
  <!ELEMENT device (type, inputsensor, trackingstation, display+, avatartype, transmitteroffset, notrackingposition, platformpos, platformrot, platformsize)>
  <!ELEMENT type (#PCDATA)>
  <!ELEMENT inputsensor (#PCDATA)>
  <!ELEMENT trackingstation (#PCDATA)>
  <!ELEMENT display (#PCDATA)>
  <!ELEMENT avatartype (#PCDATA)>
  <!ELEMENT platformpos (x, y, z)>
  <!ELEMENT x (#PCDATA)>
  <!ELEMENT y (#PCDATA)>
  <!ELEMENT z (#PCDATA)>
  <!ELEMENT platformrot (yaw)>
  <!ELEMENT yaw (#PCDATA)>
  <!ELEMENT platformsize (width, depth)>
  <!ELEMENT width (#PCDATA)>
  <!ELEMENT depth (#PCDATA)>

  <!ELEMENT user (stereo, headtrackingstation, startplatform, warnings)>
  <!ELEMENT stereo (#PCDATA)>
  <!ELEMENT headtrackingstation (#PCDATA)>
  <!ELEMENT startplatform (#PCDATA)>
  <!ELEMENT warnings (#PCDATA)>

=== Manko10/navigation-viewing-framework/configs/kerberos_agenor_wall_desktop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "config.dtd">

<setup>

  <global>

    <groundfollowing>
      <activated>True</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <animatecoupling>True</animatecoupling>
    <movementtraces>True</movementtraces>

  </global>

  <device>

    <type>NewSpheron</type>

    <inputsensor>device-new-spheron</inputsensor>

    <trackingstation>tracking-new-spheron</trackingstation>

    <display>large_powerwall</display>

    <avatartype>joseph</avatartype>

    <transmitteroffset>
      <x>0.0</x>
      <y>0.043</y>
      <z>1.6</z>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.75</y>
      <z>1.5</z>
    </notrackingposition>

    <platformpos>
      <x>0.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

    <platformsize>
      <width>3.8</width>
      <depth>3.6</depth>
    </platformsize>

  </device>

  <device>

    <type>Spacemouse</type>

    <inputsensor>device-spacemouse</inputsensor>

    <display>agenor_display</display>

    <avatartype>joseph</avatartype>

    <transmitteroffset>
      <x>0.0</x>
      <y>0.043</y>
      <z>1.6</z>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.2</y>
      <z>0.6</z>
    </notrackingposition>

    <platformpos>
      <x>0.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

  </device>

  <!-- First User -->
  
  <user>

    <vip>False</vip>

    <headtrackingstation>tracking-dlp-glasses-1</headtrackingstation>

    <glasses>1</glasses>

    <startplatform>0</startplatform>

    <warnings>True</warnings>

  </user>

  <!-- Second User -->
  
  <user>

    <vip>False</vip>

    <headtrackingstation>tracking-dlp-glasses-4</headtrackingstation>

    <glasses>4</glasses>

    <startplatform>0</startplatform>

    <warnings>True</warnings>

  </user>

  <!-- Third User -->
  
  <user>

    <vip>False</vip>

    <headtrackingstation>tracking-dlp-glasses-5</headtrackingstation>

    <glasses>5</glasses>

    <startplatform>0</startplatform>

    <warnings>True</warnings>

  </user>

  <!-- Fourth User -->
  
  <user>

    <vip>False</vip>

    <headtrackingstation>tracking-dlp-glasses-6</headtrackingstation>

    <glasses>6</glasses>

    <startplatform>0</startplatform>

    <warnings>True</warnings>

  </user>



  <!-- Desktop user -->

  <user>

    <vip>False</vip>

    <startplatform>1</startplatform>

    <warnings>False</warnings>

  </user>


</setup>

=== Manko10/navigation-viewing-framework/configs/controller_spacemouse_101.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "config.dtd">

<setup>

  <global>
    
    <transmitteroffset>
      <x>0.0</x>
      <y>0.043</y>
      <z>1.6</z>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.75</y>
      <z>1.5</z>
    </notrackingposition>

    <groundfollowing>
      <activated>True</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <animatecoupling>True</animatecoupling>
    <movementtraces>True</movementtraces>

  </global>

  <device>

    <hostname>atalante</hostname>

    <type>XBoxController</type>

    <inputsensor>device-xbox-1</inputsensor>

    <trackingstation>tracking-oculus-front</trackingstation>

    <platformpos>
      <x>-2.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

    <platformsize>
      <width>3.8</width>
      <depth>3.6</depth>
    </platformsize>

  </device>

  <device>

    <hostname>atalante</hostname>

    <type>Spacemouse</type>

    <inputsensor>device-spacemouse</inputsensor>

    <platformpos>
      <x>2.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

  </device>
        
  <!-- First OVR User -->

  <user>

    <type>OVRUser</type>

    <headtrackingstation>tracking-oculus-front</headtrackingstation>

    <startplatform>0</startplatform>

    <warnings>False</warnings>

    <display>:0.0</display>

  </user>

  <!-- First Desktop User -->
  <user>

    <type>DesktopUser</type>

    <startplatform>1</startplatform>

    <windowsize>
      <width>1280</width>
      <height>800</height>
    </windowsize>

    <screensize>
      <width>1.06</width>
      <height>0.74</height>
    </screensize>

    <display>:0.0</display>

  </user>
  

</setup>

=== Manko10/navigation-viewing-framework/configs/presentation_112.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "config.dtd">

<setup>
  
  <global>
    
    <transmitteroffset>
      <x>0.0</x>
      <y>0.0043</y>
      <z>1.6</z>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.75</y>
      <z>1.5</z>
    </notrackingposition>

    <groundfollowing>
      <activated>True</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <animatecoupling>True</animatecoupling>
    <movementtraces>True</movementtraces>

  </global>
  
  <device>

    <hostname>kerberos</hostname>

    <type>NewSpheron</type>

    <inputsensor>device-new-spheron</inputsensor>

    <trackingstation>tracking-new-spheron</trackingstation>

    <platformpos>
      <x>-2.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

    <platformsize>
      <width>3.8</width>
      <depth>3.6</depth>
    </platformsize>

  </device>

  <device>

    <hostname>orestes</hostname>

    <type>Spacemouse</type>

    <inputsensor>device-spacemouse</inputsensor>

    <platformpos>
      <x>2.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

  </device>

  <device>

    <hostname>nestor</hostname>

    <type>XBoxController</type>

    <inputsensor>device-xbox-1</inputsensor>

    <trackingstation>tracking-oculus-front</trackingstation>

    <platformpos>
      <x>-2.0</x>
      <y>0.0</y>
      <z>15.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

    <platformsize>
      <width>3.8</width>
      <depth>3.6</depth>
    </platformsize>

  </device>

  <device>

    <hostname>nestor</hostname>

    <type>XBoxController</type>

    <inputsensor>device-xbox-2</inputsensor>

    <trackingstation>tracking-oculus-stag</trackingstation>

    <platformpos>
      <x>2.0</x>
      <y>0.0</y>
      <z>15.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

    <platformsize>
      <width>3.8</width>
      <depth>3.6</depth>
    </platformsize>

  </device>

  <!-- Power Wall User on kerberos -->
  <user>

    <type>LargePowerWallUser</type>

    <headtrackingstation>tracking-dlp-glasses-1</headtrackingstation>

    <startplatform>0</startplatform>

    <warnings>True</warnings>

    <display>:0.0</display>

  </user>

  <!-- Desktop User on orestes -->

  <user>

    <type>DesktopUser</type>

    <startplatform>1</startplatform>

    <windowsize>
      <width>1920</width>
      <height>1080</height>
    </windowsize>

    <screensize>
      <width>1.6</width>
      <height>1.0</height>
    </screensize>

    <display>:0.0</display>

  </user>

  <!-- First OVR User on nestor -->
  
  <user>

    <type>OVRUser</type>

    <headtrackingstation>tracking-oculus-front</headtrackingstation>

    <startplatform>2</startplatform>

    <warnings>True</warnings>
    
    <display>:0.0</display>

  </user>

  <!-- Second OVR User on nestor -->
  
  <user>

    <type>OVRUser</type>

    <headtrackingstation>tracking-oculus-stag</headtrackingstation>

    <startplatform>3</startplatform>

    <warnings>True</warnings>
    
    <display>:0.0</display>

  </user>
  
   

</setup>

=== Manko10/navigation-viewing-framework/configs/kerberos_nestor_separate_navigation.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "config.dtd">

<setup>

  <global>

    <groundfollowing>
      <activated>True</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <animatecoupling>True</animatecoupling>
    <movementtraces>True</movementtraces>

  </global>


  <device>

    <type>Spacemouse</type>

    <inputsensor>device-spacemouse</inputsensor>

    <display>large_powerwall</display>

    <avatartype>joseph</avatartype>

    <transmitteroffset>
      <x>0.0</x>
      <y>0.043</y>
      <z>1.6</z>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.75</y>
      <z>1.6</z>
    </notrackingposition>

    <platformpos>
      <x>-2.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

    <platformsize>
      <width>3.8</width>
      <depth>3.6</depth>
    </platformsize>

  </device>


  <device>

    <type>KeyboardMouse</type>

    <display>nestor_display</display>

    <avatartype>joseph_table</avatartype>

    <transmitteroffset>
      <x>0.0</x>
      <y>1.06</y>
      <z>0.77</z>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.2</y>
      <z>0.6</z>
    </notrackingposition>

    <platformpos>
      <x>-2.0</x>
      <y>0.0</y>
      <z>10.0</z>
    </platformpos>

    <platformrot>
      <yaw>180.0</yaw>
    </platformrot>

  </device>

  <!-- DLP First User -->
  
  <user>

    <stereo>True</stereo>

    <headtrackingstation>tracking-dlp-glasses-1</headtrackingstation>

    <startplatform>0</startplatform>

    <warnings>True</warnings>

  </user>


  <!-- DLP Second User -->
  
  <user>

    <stereo>True</stereo>

    <headtrackingstation>tracking-dlp-glasses-4</headtrackingstation>

    <startplatform>0</startplatform>

    <warnings>True</warnings>

  </user>


  <!-- DLP Third User -->
  
  <user>

    <stereo>True</stereo>

    <headtrackingstation>tracking-dlp-glasses-5</headtrackingstation>

    <startplatform>0</startplatform>

    <warnings>True</warnings>

  </user>


  <!-- DLP Forth User -->
  
  <user>

    <stereo>True</stereo>

    <headtrackingstation>tracking-dlp-glasses-6</headtrackingstation>

    <startplatform>0</startplatform>

    <warnings>True</warnings>

  </user>


  <!-- Desktop First User -->
  
  <user>

    <stereo>False</stereo>

    <startplatform>1</startplatform>

    <warnings>False</warnings>

  </user>
  
    
</setup>

=== Manko10/navigation-viewing-framework/configs/atalante_oculus.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "config.dtd">

<setup>

  <global>

    <animatecoupling>True</animatecoupling>

  </global>

  <device>

    <type>Spacemouse</type>

    <inputsensor>device-spacemouse</inputsensor>

    <display>oculus_rift_atalante</display>

    <avatartype>joseph</avatartype>

    <transmitteroffset>
      <x>0.0</x>
      <y>0.043</y>
      <z>1.6</z>
      <rx>0.0</rx>
      <ry>0.0</ry>
      <rz>0.0</rz>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.2</y>
      <z>0.6</z>
    </notrackingposition>

    <platformpos>
      <x>-2.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

    <platformsize>
      <width>3.8</width>
      <depth>3.6</depth>
    </platformsize>

    <groundfollowing>
      <activated>True</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <movementtraces>True</movementtraces>

  </device>
        

  <!-- First User -->
  
  <user>

    <vip>False</vip>

    <headtrackingstation>tracking-oculus-stag</headtrackingstation>

    <hmdsensor>oculus-0</hmdsensor>

    <startplatform>0</startplatform>

    <warnings>True</warnings>

  </user>

</setup>

=== Manko10/navigation-viewing-framework/configs/nestor_atalante_kombi_desktop.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "config.dtd">

<setup>

  <global>

    <groundfollowing>
      <activated>True</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <animatecoupling>True</animatecoupling>
    <movementtraces>True</movementtraces>

  </global>

  <device>

    <type>Spacemouse</type>

    <inputsensor>device-spacemouse</inputsensor>

    <display>nestor_display</display>

    <display>atalante_display</display>

    <avatartype>joseph</avatartype>

    <transmitteroffset>
      <x>0.0</x>
      <y>0.043</y>
      <z>1.6</z>
      <rx>0.0</rx>
      <ry>0.0</ry>
      <rz>0.0</rz>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.0</y>
      <z>0.6</z>
    </notrackingposition>

    <platformpos>
      <x>-2.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

  </device>
        

  <!-- First User -->
  
  <user>

    <vip>True</vip>

    <startplatform>0</startplatform>

    <warnings>False</warnings>

  </user>

</setup>

=== Manko10/navigation-viewing-framework/configs/spacemouse_100.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "config.dtd">

<setup>

  <global>

    <groundfollowing>
      <activated>True</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <animatecoupling>True</animatecoupling>
    <movementtraces>True</movementtraces>

  </global>

  <device>

    <type>Spacemouse</type>

    <inputsensor>device-spacemouse</inputsensor>

    <display>atalante_display</display>

    <avatartype>kinect</avatartype>

    <transmitteroffset>
      <x>0.0</x>
      <y>0.043</y>
      <z>1.6</z>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.75</y>
      <z>1.5</z>
    </notrackingposition>

    <platformpos>
      <x>-2.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

  </device>
        

  <!-- First Desktop User -->
  
  <user>

    <type>DesktopUser</type>

    <startplatform>0</startplatform>

  </user>
   

</setup>

=== Manko10/navigation-viewing-framework/configs/newspheron_100.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE setup SYSTEM "config.dtd">

<setup>
  
  <global>
    
    <transmitteroffset>
      <x>0.0</x>
      <y>0.0043</y>
      <z>1.6</z>
    </transmitteroffset>

    <notrackingposition>
      <x>0.0</x>
      <y>1.75</y>
      <z>1.5</z>
    </notrackingposition>

    <groundfollowing>
      <activated>True</activated>
      <raystartheight>0.75</raystartheight>
    </groundfollowing>

    <animatecoupling>True</animatecoupling>
    <movementtraces>True</movementtraces>

  </global>
  
  <device>

    <hostname>nestor</hostname>

    <type>NewSpheron</type>

    <inputsensor>device-new-spheron</inputsensor>

    <trackingstation>tracking-new-spheron</trackingstation>

    <platformpos>
      <x>-2.0</x>
      <y>0.0</y>
      <z>12.0</z>
    </platformpos>

    <platformrot>
      <yaw>0.0</yaw>
    </platformrot>

    <platformsize>
      <width>3.8</width>
      <depth>3.6</depth>
    </platformsize>

  </device>

  <!-- First Desktop User -->
  
  <user>

    <type>DesktopUser</type>

    <startplatform>0</startplatform>

    <windowsize>
      <width>1920</width>
      <height>1080</height>
    </windowsize>

    <screensize>
      <width>1.6</width>
      <height>1.0</height>
    </screensize>

    <display>:0.0</display>

  </user>
  
   

</setup>
